In [194]:
using Rocket
using ReactiveMP
using GraphPPL
using BenchmarkTools
using Distributions

In [225]:
@macroexpand @model function smoothing(n_observations, noise_mean, noise_var)
    
    x_prior_mean = datavar(Float64)
    x_prior_var  = datavar(Float64)

    x_prior ~ NormalMeanVariance(x_prior_mean, x_prior_var)

    x = randomvar(n_observations)
    y = datavar(Float64, n_observations)

    x[1] = x_prior

    for i in 2:n_observations
       x[i] ~ x[i - 1] + 1.0
       y[i] ~ x[i] + NormalMeanVariance(noise_mean, inv(inv(noise_var)))
    end

    return x_prior_mean, x_prior_var, x, y
end

quote
    #= /Users/bvdmitri/.julia/dev/GraphPPL.jl/src/GraphPPL.jl:204 =#
    function smoothing(n_observations, noise_mean, noise_var)
        #= /Users/bvdmitri/.julia/dev/GraphPPL.jl/src/GraphPPL.jl:204 =#
        #= /Users/bvdmitri/.julia/dev/GraphPPL.jl/src/GraphPPL.jl:205 =#
        var"##model#5890" = Model()
        #= /Users/bvdmitri/.julia/dev/GraphPPL.jl/src/GraphPPL.jl:206 =#
        begin
            #= In[225]:1 =#
            #= In[225]:3 =#
            x_prior_mean = ReactiveMP.datavar(var"##model#5890", :x_prior_mean, Dirac{GraphPPL.ensure_type(Float64)})
            #= In[225]:4 =#
            x_prior_var = ReactiveMP.datavar(var"##model#5890", :x_prior_var, Dirac{GraphPPL.ensure_type(Float64)})
            #= In[225]:6 =#
            (var"##5894", x_prior) = ReactiveMP.make_node(var"##model#5890", NormalMeanVariance, ReactiveMP.AutoVar(:x_prior), ReactiveMP.as_variable(var"##model#5890", Symbol("##arg#5895"), x_prior_mean), ReactiveMP.as_variable(var"##model#5890", 

In [230]:
@model function smoothing(n_observations, noise_mean, noise_var)
    
    x_prior_mean = datavar(Float64)
    x_prior_var  = datavar(Float64)

    x_prior ~ NormalMeanVariance(x_prior_mean, x_prior_var)

    x = randomvar(n_observations)
    y = datavar(Float64, n_observations)

    x[1] = x_prior

    for i in 2:n_observations
       x[i] ~ x[i - 1] + 1.0
       y[i] ~ x[i] + NormalMeanVariance(noise_mean, inv(noise_var))
    end

    return x_prior_mean, x_prior_var, x, y
end

smoothing (generic function with 1 method)

In [231]:
noise_real_mean = -10.0
noise_real_var  = 100.0

n = 500
data = map(d -> d + rand(Normal(noise_real_mean, sqrt(noise_real_var))), collect(1:n));

In [232]:
function inference(; data, x_prior)
    n = length(data)
    
    x_prior_mean, x_prior_var, x, y = smoothing(n, noise_real_mean, noise_real_var);

    subscriptions = Vector{Teardown}(undef, n)
    marginals = Vector{Marginal}(undef, n)
    
    for i in 1:n
         @inbounds subscriptions[i] = subscribe!(getmarginal(x[i]), (m) -> marginals[i] = m)
    end
    
    update!(x_prior_mean, mean(x_prior))
    update!(x_prior_var, var(x_prior))
    
    for i in 1:n
        @inbounds update!(y[i], data[i])
    end
    
    foreach(unsubscribe!, subscriptions)
    
    return marginals
end

inference (generic function with 1 method)

In [233]:
inference(
    data = data,
    x_prior = NormalMeanVariance(0.0, 10000.0)
)

ConstVariable{Dirac{Float64}}(Symbol("##nvar#5932"), Dirac{Float64}(0.1), ReactiveMP.ConstVariableProps(nothing, nothing))
ConstVariable{Dirac{Float64}}(Symbol("##nvar#5932"), Dirac{Float64}(0.1), ReactiveMP.ConstVariableProps(nothing, nothing))
ConstVariable{Dirac{Float64}}(Symbol("##nvar#5932"), Dirac{Float64}(0.1), ReactiveMP.ConstVariableProps(nothing, nothing))
ConstVariable{Dirac{Float64}}(Symbol("##nvar#5932"), Dirac{Float64}(0.1), ReactiveMP.ConstVariableProps(nothing, nothing))
ConstVariable{Dirac{Float64}}(Symbol("##nvar#5932"), Dirac{Float64}(0.1), ReactiveMP.ConstVariableProps(nothing, nothing))
ConstVariable{Dirac{Float64}}(Symbol("##nvar#5932"), Dirac{Float64}(0.1), ReactiveMP.ConstVariableProps(nothing, nothing))
ConstVariable{Dirac{Float64}}(Symbol("##nvar#5932"), Dirac{Float64}(0.1), ReactiveMP.ConstVariableProps(nothing, nothing))
ConstVariable{Dirac{Float64}}(Symbol("##nvar#5932"), Dirac{Float64}(0.1), ReactiveMP.ConstVariableProps(nothing, nothing))
ConstVariable{Di

500-element Array{Marginal,1}:
 Marginal{NormalMeanVariance{Float64}}(NormalMeanVariance{Float64}(μ=0.8763982055246959, v=0.0002004007975871584))
 Marginal{NormalMeanVariance{Float64}}(NormalMeanVariance{Float64}(μ=1.876398205524696, v=0.00020040079758715837))
 Marginal{NormalMeanVariance{Float64}}(NormalMeanVariance{Float64}(μ=2.8763982055246955, v=0.00020040079758715834))
 Marginal{NormalMeanVariance{Float64}}(NormalMeanVariance{Float64}(μ=3.8763982055246964, v=0.0002004007975871584))
 Marginal{NormalMeanVariance{Float64}}(NormalMeanVariance{Float64}(μ=4.876398205524696, v=0.00020040079758715834))
 Marginal{NormalMeanVariance{Float64}}(NormalMeanVariance{Float64}(μ=5.876398205524695, v=0.00020040079758715837))
 Marginal{NormalMeanVariance{Float64}}(NormalMeanVariance{Float64}(μ=6.876398205524695, v=0.00020040079758715837))
 Marginal{NormalMeanVariance{Float64}}(NormalMeanVariance{Float64}(μ=7.876398205524695, v=0.00020040079758715834))
 Marginal{NormalMeanVariance{Float64}}(NormalMea

In [209]:
dump(:(1.0 / begin
    a = 1
    a
end))

Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol /
    2: Float64 1.0
    3: Expr
      head: Symbol block
      args: Array{Any}((4,))
        1: LineNumberNode
          line: Int64 2
          file: Symbol In[209]
        2: Expr
          head: Symbol =
          args: Array{Any}((2,))
            1: Symbol a
            2: Int64 1
        3: LineNumberNode
          line: Int64 3
          file: Symbol In[209]
        4: Symbol a


In [84]:
@btime Symbol(join(ss, :_))

  666.089 ns (8 allocations: 352 bytes)


:a_a_a_a_a_a_a_a_a_a

In [89]:
@btime Symbol(ReactiveMP.with_separator(:_, ss)...)

  1.669 μs (42 allocations: 1.52 KiB)


:a_a_a_a_a_a_a_a_a_a

In [109]:
@btime datavar(:name, Float64, 100, 100)

  12.146 ms (248309 allocations: 10.48 MiB)


100×100 Array{DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64},2}:
 DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_1_1, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))    …  DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_1_100, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))
 DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_2_1, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))       DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_2_100, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))
 DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_3_1, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))       DataVariable{Subject{Message{Float64},AsapScheduler

In [108]:
@btime datavar(:name, Float64, 100, 100)

  14.999 ms (250010 allocations: 10.22 MiB)


100×100 Array{DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64},2}:
 DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_1_1, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))    …  DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_1_100, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))
 DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_2_1, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))       DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_2_100, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))
 DataVariable{Subject{Message{Float64},AsapScheduler,AsapScheduler},Float64}(:name_3_1, Subject(Message{Float64}, AsapScheduler), DataVariableProps(nothing, nothing))       DataVariable{Subject{Message{Float64},AsapScheduler

In [103]:
for index in CartesianIndices(axes(ss))
    println(join(index.I, :_))
end

1
2
3
4
5
6
7
8
9
10


In [99]:
r = CartesianIndices(axes(ss))[1]

CartesianIndex(1,)

In [104]:
?CartesianIndex

search: CartesianIndex CartesianIndices



```
CartesianIndex(i, j, k...)   -> I
CartesianIndex((i, j, k...)) -> I
```

Create a multidimensional index `I`, which can be used for indexing a multidimensional array `A`.  In particular, `A[I]` is equivalent to `A[i,j,k...]`.  One can freely mix integer and `CartesianIndex` indices; for example, `A[Ipre, i, Ipost]` (where `Ipre` and `Ipost` are `CartesianIndex` indices and `i` is an `Int`) can be a useful expression when writing algorithms that work along a single dimension of an array of arbitrary dimensionality.

A `CartesianIndex` is sometimes produced by [`eachindex`](@ref), and always when iterating with an explicit [`CartesianIndices`](@ref).

# Examples

```jldoctest
julia> A = reshape(Vector(1:16), (2, 2, 2, 2))
2×2×2×2 Array{Int64,4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16

julia> A[CartesianIndex((1, 1, 1, 1))]
1

julia> A[CartesianIndex((1, 1, 1, 2))]
9

julia> A[CartesianIndex((1, 1, 2, 1))]
5
```


In [102]:
dump(r.I)

Tuple{Int64}
  1: Int64 1


In [122]:
?@assert

```
@assert cond [text]
```

Throw an [`AssertionError`](@ref) if `cond` is `false`. Preferred syntax for writing assertions. Message `text` is optionally displayed upon assertion failure.

!!! warning
    An assert might be disabled at various optimization levels. Assert should therefore only be used as a debugging tool and not used for authentication verification (e.g., verifying passwords), nor should side effects needed for the function to work correctly be used inside of asserts.


# Examples

```jldoctest
julia> @assert iseven(3) "3 is an odd number!"
ERROR: AssertionError: 3 is an odd number!

julia> @assert isodd(3) "What even are numbers?"
```
